Stat svc
Bikochu/java-explore-with-me pull request #3
Opened 2023-06-27 13:56 UTC by Bikochu

2023-06-29 20:16 UTC, Donald522 requested changes
Привет!

Все хорошо. Пара моментов:
 - добавить логов, чтобы сервис был наблюдаемым
 - добавить индексы на нужные колонки в БД, чтобы это все работало быстро

2023-06-29 20:16 UTC, Donald522 commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/server/controller/StatsController.java
> +        return statsService.getStats(start, end, uris, unique);
Логи стоит добавить

2023-06-29 20:16 UTC, Donald522 commented on stats/stats-server/src/main/resources/schema.sql
> +uri VARCHAR(255) NOT NULL,
По uri и created нужно добавить индексы, тк по этим полям мы делаем запросы

2023-06-29 21:09 UTC, Bikochu commented on stats/stats-server/src/main/resources/schema.sql
> +uri VARCHAR(255) NOT NULL,
Добавил в таблицу индексы по uri и created.

2023-06-29 21:25 UTC, Bikochu commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/server/controller/StatsController.java
> +        return statsService.getStats(start, end, uris, unique);
Добавил логи в контроллер.

2023-06-30 13:19 UTC, Donald522 approved these changes

2023-06-30 15:15 UTC, merged