Main svc
Bikochu/java-explore-with-me pull request #4
Opened 2023-07-04 15:13 UTC by Bikochu

2023-07-07 21:12 UTC, Donald522 requested changes
Привет!

По большому счету все отлично, есть мелкие замечания

2023-07-07 21:12 UTC, Donald522 commented on main/pom.xml
> +        <!--<dependency>
Комментарии удалить надо

2023-07-07 21:12 UTC, Donald522 commented on main/src/main/java/ru/practicum/ewm/locations/dto/LocationDto.java
> +    Float lat;
Почему не double?

2023-07-07 21:12 UTC, Donald522 commented on main/src/main/java/ru/practicum/ewm/error/ConflictHandler.java
> +    public ApiError handleNotFoundException(final DataIntegrityViolationException e) {
Почему метод называется NotFound, но возвращаем 409?

2023-07-07 21:12 UTC, Donald522 commented on main/src/main/java/ru/practicum/ewm/users/dto/UserShortDto.java
> +    Long id;
По спецификации это поле тоже не может быть null

2023-07-08 13:12 UTC, Bikochu commented on main/src/main/java/ru/practicum/ewm/locations/dto/LocationDto.java
> +    Float lat;
Делал согласно спецификации. Там было указано $float. 
Так же хочу отметить, что обычно в геолокации используют координаты с 6-7 знаками после точки, что обеспечивает точность до 1 метра. Float - отлично подходит для предоставления такой информации, так как его диапазон около 7 десятичных цифр. 
Но возможно я не прав, поэтому исправил согласно вашим рекомендациям!

2023-07-08 13:12 UTC, Bikochu commented on main/pom.xml
> +        <!--<dependency>
Удалил, а так же лишние зависимости удалил.

2023-07-08 13:14 UTC, Bikochu commented on main/src/main/java/ru/practicum/ewm/users/dto/UserShortDto.java
> +    Long id;
Да, вы правы, проглядел этот момент. Исправил!

2023-07-08 13:33 UTC, Bikochu commented on main/src/main/java/ru/practicum/ewm/error/ConflictHandler.java
> +    public ApiError handleNotFoundException(final DataIntegrityViolationException e) {
Да вы правы. При работе над ошибками убирал лишнее и недоглядел за названием. Исправил согласно вашим рекомендациям.

2023-07-08 17:21 UTC, Donald522 approved these changes

2023-07-08 22:32 UTC, merged