Feature rating events
Bikochu/java-explore-with-me pull request #5
Opened 2023-07-10 21:16 UTC by Bikochu

2023-07-11 20:16 UTC, Donald522 requested changes
Привет!

Написал вопросы и замечания.

2023-07-11 20:16 UTC, Donald522 commented on main/src/main/java/ru/practicum/ewm/rating/controller/RatingControllerPrivate.java
> +public class RatingControllerPrivate {
Не очень понятно, почему для того, чтобы поставить/убрать лайк надо аж 3 метода апи
Как фронтенд должен понимать какой из методов вызвать?

Я бы вообще 1 метод сделал.

2023-07-11 20:16 UTC, Donald522 commented on main/src/main/java/ru/practicum/ewm/rating/model/Rating.java
> +    Long likerId;
liker звучит как-то не очень)
Может user_id лучше?

2023-07-11 20:16 UTC, Donald522 commented on main/src/main/resources/schema.sql
> +rate DOUBLE PRECISION
Не очень понял зачем пользователю это. Как используется в конечном интерфейсе информация о том, сколько пользователь поставил лайков и дизлайков?

2023-07-11 20:16 UTC, Donald522 commented on main/src/main/resources/schema.sql
> +rate DOUBLE PRECISION,
Думаю на это поле нужен индекс.
Какой запрос хибернейт строит для получения списка событий отсортированных по рейтингу?

2023-07-12 12:43 UTC, Bikochu commented on main/src/main/resources/schema.sql
> +rate DOUBLE PRECISION
Данные likes и dislikes нужны для формирования поля rate. В методах добавления/изменения/удаления рейтинга была допущена ошибка. Исправил бизнес логику. Теперь пользователь, который ставит "Лайк" Эвенту, он автоматически ставил "Лайк" инициатору Эвента. Таким образом будет запись likes и dislikes у инициатора и формироваться рейтинг пользователя.

2023-07-12 12:46 UTC, Bikochu commented on main/src/main/resources/schema.sql
> +rate DOUBLE PRECISION,
Добавил полю rate индекс. 
Для формирования списка событий сортированных по полю rate, использую отсечку всех эвентов с полем rate=null. Таким образом пользователю показывается список эвентов у которых есть не нулевой рейтинг отсортированный в зависимости от запроса. (HIGH или LOW).

2023-07-12 20:35 UTC, Donald522 requested changes
Привет!

Насчет апи все еще не очень понятно почему там 3 метода, которые ты схлопнул в 1 (но на самом деле в точки зрения внешнего апи там все те же 3 метода)

Можем в пачке обсудить в лс, чтобы итерации не тратить.

2023-07-12 20:35 UTC, Donald522 commented on main/src/main/java/ru/practicum/ewm/rating/controller/RatingControllerPrivate.java
> +public class RatingControllerPrivate {
Ну так проще то не стало. Суть осталась та же - просто вместо 3 методов стало 3 ветки if

Вот например я фронтенд разработчик и делаю ui для нашего сервиса. Ты бэкенд разработчик.
Ты мне отдаешь такую спеку апи, мне не понятно, как мне вызывать этот метод.
Чем отличается изменение лайка от добавления лайка и от удаления? На мой взгляд это все изменение. 

Либо объясни какой будет дизайн у приложение (какие там кнопки, сколько их и тд)

2023-07-13 19:37 UTC, Donald522 approved these changes

2023-07-17 12:17 UTC, merged